name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g eas-cli
      - run: npm install
      - run: eas build --platform android --profile preview --non-interactive --local
      - uses: actions/upload-artifact@v4
        with:
          name: app-apk
          path: '*.apk'
